# Model config file
# Directories and paths
train_dir: data/images/train
train_label_path: data/annotations/train_annotations.csv
val_dir: data/images/val
val_label_path: data/annotations/val_annotations.csv
checkpoint_dir: output/checkpoints
label_map: data/annotations/label_map.json
rgb_norm: data/annotations/dataset_norm.json

# Model settings
architecture: tf_efficientdet_d1
img_size: 1024
num_classes: 3
wbf_iou_threshold: 0.5
max_det_per_image: 300

# Optimizer
optimizer: 
  name: AdamW
  lr: 0.001
  momentum: 0.99
  nesterov: True
  weight_decay: 0.01
  filter_bias_and_bn: True

# Learning Rate Scheduler
scheduler: 
  name: ExponentialLR
  gamma: 0.8

# Training Settings
run_name: 'test'
epochs: 20
batch_size: 2
device: cpu